Detect number of warnings?

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1700,7 +1700,28 @@ workflows:
         - scheme: Fennec
         - configuration: Fennec_Testing
         - destination: platform=iOS Simulator,name=iPhone 16,OS=18.2
-        - xcodebuild_options: '"COMPILER_INDEX_STORE_ENABLE=NO" "CODE_SIGN_IDENTITY=" "CODE_SIGNING_REQUIRED=NO" "CODE_SIGNING_ALLOWED=NO" "SWIFT_UPCOMING_FEATURE_EXISTENTIAL_ANY=YES" "SWIFT_UPCOMING_FEATURE_REGION_BASED_ISOLATION=YES"'
+        - xcodebuild_options: '"COMPILER_INDEX_STORE_ENABLE=NO" "CODE_SIGN_IDENTITY=" "CODE_SIGNING_REQUIRED=NO" "CODE_SIGNING_ALLOWED=NO" "SWIFT_TREAT_WARNINGS_AS_ERRORS = NO" "SWIFT_UPCOMING_FEATURE_EXISTENTIAL_ANY=YES" "SWIFT_UPCOMING_FEATURE_REGION_BASED_ISOLATION=YES"'
+    - script@1.2.1:
+        title: Detect number of warnings
+        is_always_run: true
+        inputs:
+        - content: |
+            set -e
+            set -x
+
+            echo "bitrise_xcode"
+            COUNT_XCUI=$(./test-fixtures/generate-metrics.sh /Users/vagrant/git/xcodebuild_fennec.log all)
+
+            envman add --key SHOW_WARNING_IN_SLACK --value Show_Warnings
+            envman add --key SHOW_WARNING_COUNT_XCUI --value "$COUNT_XCUI"
+
+            STR=$COUNT_XCUI
+            SUB='greater'
+            if [[ "$STR" == *"$SUB"* ]]; then
+                echo "Failure, the number of warnings increased"
+                exit 1
+            fi
+
   #
   # *****%*****%***** FOCUS WORKFLOWS *****%*****%*****
   #
